version: '3.4'

services:
  db:
    container_name: 'dev-gauntlet'
    image: 'postgres'
    platform: linux/amd64
    volumes:
      - './.postgres-data:/var/lib/postgresql/data'
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 2000:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "db"
      POSTGRES_DB: "dev-gauntlet"
